openapi: 3.0.0
info:
  title: PetCareHub API
  version: 1.0.0
  description: 寵物照護任務管理 SaaS 的 RESTful API 規格
servers:
  - url: http://localhost/api/v1
    description: 開發環境伺服器
  - url: https://api.staging.petcarehub.com/api/v1
    description: Staging 環境伺服器
  - url: https://api.petcarehub.com/api/v1
    description: 正式環境伺服器
tags:
  - name: Auth
    description: 認證相關操作
  - name: Users
    description: 使用者相關操作
  - name: Pets
    description: 寵物相關操作
  - name: Tasks
    description: 寵物照護任務操作
  - name: AI
    description: AI 推薦服務
components:
  securitySchemes:
    sanctum:
      type: http
      scheme: bearer
      bearerFormat: 'Sanctum'
      description: Laravel Sanctum API Token
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 使用者 ID
          example: 1
        name:
          type: string
          description: 使用者名稱
          example: John Doe
        email:
          type: string
          format: email
          description: 電子郵件
          example: john.doe@example.com
      required:
        - name
        - email
    Pet:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 寵物 ID
          readOnly: true
          example: 101
        user_id:
          type: integer
          format: int64
          description: 所屬使用者 ID
          readOnly: true
          example: 1
        name:
          type: string
          description: 寵物名稱
          example: Max
        species:
          type: string
          description: 物種 (e.g., dog, cat)
          example: dog
        breed:
          type: string
          nullable: true
          description: 品種
          example: Golden Retriever
        birth_date:
          type: string
          format: date
          nullable: true
          description: 出生日期 (YYYY-MM-DD)
          example: 2022-05-15
        weight:
          type: number
          format: float
          nullable: true
          description: 體重 (公斤)
          example: 28.5
        created_at:
          type: string
          format: date-time
          readOnly: true
          example: 2023-10-26T10:00:00Z
        updated_at:
          type: string
          format: date-time
          readOnly: true
          example: 2023-10-26T10:00:00Z
      required:
        - name
        - species
    CareTask:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 任務 ID
          readOnly: true
          example: 201
        pet_id:
          type: integer
          format: int64
          description: 所屬寵物 ID
          example: 101
        user_id:
          type: integer
          format: int64
          description: 所屬使用者 ID
          readOnly: true
          example: 1
        title:
          type: string
          description: 任務標題
          example: 每日散步
        description:
          type: string
          nullable: true
          description: 任務詳細描述
          example: 帶狗狗去公園散步 30 分鐘
        due_date:
          type: string
          format: date-time
          nullable: true
          description: 預計完成日期時間 (ISO 8601)
          example: 2023-10-27T18:00:00Z
        status:
          type: string
          description: 任務狀態
          enum: [pending, completed, overdue]
          default: pending
          example: pending
        is_recurring:
          type: boolean
          description: 是否為週期性任務
          default: false
          example: false
        recurring_rule:
          type: object
          nullable: true
          description: 週期性任務規則 (JSON)
          example: { "frequency": "daily", "interval": 1 }
        completed_at:
          type: string
          format: date-time
          nullable: true
          description: 任務完成時間
          example: 2023-10-27T17:30:00Z
        created_at:
          type: string
          format: date-time
          readOnly: true
          example: 2023-10-26T09:00:00Z
        updated_at:
          type: string
          format: date-time
          readOnly: true
          example: 2023-10-26T09:00:00Z
      required:
        - pet_id
        - title
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: 錯誤訊息
          example: "The given data was invalid."
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: 驗證錯誤詳細資訊 (僅在 422 時出現)
          example:
            name:
              - "The name field is required."
            species:
              - "The species field is required."
      required:
        - message
  parameters:
    AuthorizationHeader:
      in: header
      name: Authorization
      schema:
        type: string
        format: 'Bearer {token}'
      required: true
      description: 'Bearer token for authentication. Example: Bearer 1|abcdef...'
    ContentTypeHeader:
      in: header
      name: Content-Type
      schema:
        type: string
        enum: ['application/json']
      required: true
      description: 'Specifies the request body format. Must be application/json.'
paths:
  /user:
    get:
      summary: 取得當前認證使用者資訊
      tags: [Auth]
      security:
        - sanctum: []
      responses:
        '200':
          description: 成功取得使用者資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: 未經授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /pets:
    get:
      summary: 取得所有寵物
      tags: [Pets]
      security:
        - sanctum: []
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader' # Global header
        - $ref: '#/components/parameters/ContentTypeHeader' # Global header
        - in: query
          name: species
          schema:
            type: string
          description: 依物種篩選
          example: dog
      responses:
        '200':
          description: 成功取得寵物列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '401':
          description: 未經授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: 建立新寵物
      tags: [Pets]
      security:
        - sanctum: []
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/ContentTypeHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Luna
                species:
                  type: string
                  example: cat
                breed:
                  type: string
                  nullable: true
                  example: Siamese
                birth_date:
                  type: string
                  format: date
                  nullable: true
                  example: 2021-03-20
                weight:
                  type: number
                  format: float
                  nullable: true
                  example: 4.5
              required:
                - name
                - species
      responses:
        '201':
          description: 寵物建立成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '401':
          description: 未經授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: 驗證失敗
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /pets/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        required: true
        description: 寵物 ID
    get:
      summary: 取得單一寵物資訊
      tags: [Pets]
      security:
        - sanctum: []
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
      responses:
        '200':
          description: 成功取得寵物資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: 寵物不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 未經授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: 更新寵物資訊
      tags: [Pets]
      security:
        - sanctum: []
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/ContentTypeHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Luna New
                weight:
                  type: number
                  format: float
                  example: 4.8
              required:
                - name
      responses:
        '200':
          description: 寵物更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: 寵物不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 未經授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: 驗證失敗
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: 刪除寵物
      tags: [Pets]
      security:
        - sanctum: []
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
      responses:
        '204':
          description: 寵物刪除成功 (無內容)
        '404':
          description: 寵物不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 未經授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /tasks:
    get:
      summary: 取得所有寵物照護任務
      tags: [Tasks]
      security:
        - sanctum: []
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/ContentTypeHeader'
        - in: query
          name: status
          schema:
            type: string
            enum: [pending, completed, overdue]
          description: 依任務狀態篩選
          example: pending
        - in: query
          name: pet_id
          schema:
            type: integer
            format: int64
          description: 依寵物 ID 篩選
          example: 101
      responses:
        '200':
          description: 成功取得任務列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CareTask'
        '401':
          description: 未經授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: 建立新照護任務
      tags: [Tasks]
      security:
        - sanctum: []
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/ContentTypeHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pet_id:
                  type: integer
                  format: int64
                  example: 101
                title:
                  type: string
                  example: 帶狗狗洗澡
                description:
                  type: string
                  nullable: true
                  example: 每月一次的洗澡服務
                due_date:
                  type: string
                  format: date-time
                  nullable: true
                  example: 2023-11-01T10:00:00Z
                status:
                  type: string
                  enum: [pending, completed, overdue]
                  default: pending
                  example: pending
              required:
                - pet_id
                - title
      responses:
        '201':
          description: 任務建立成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CareTask'
        '401':
          description: 未經授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: 驗證失敗
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /tasks/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        required: true
        description: 任務 ID
    get:
      summary: 取得單一照護任務資訊
      tags: [Tasks]
      security:
        - sanctum: []
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
      responses:
        '200':
          description: 成功取得任務資料
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CareTask'
        '404':
          description: 任務不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 未經授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: 更新照護任務資訊
      tags: [Tasks]
      security:
        - sanctum: []
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/ContentTypeHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: 帶狗狗去獸醫院
                status:
                  type: string
                  enum: [pending, completed, overdue]
                  example: completed
              required:
                - title
      responses:
        '200':
          description: 任務更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CareTask'
        '404':
          description: 任務不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 未經授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: 驗證失敗
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: 刪除照護任務
      tags: [Tasks]
      security:
        - sanctum: []
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
      responses:
        '204':
          description: 任務刪除成功 (無內容)
        '404':
          description: 任務不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 未經授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /ai/recommendations: # AI Service OpenAPI definition
    post:
      summary: 取得寵物照護推薦
      tags: [AI]
      description: 根據寵物資訊提供照護任務推薦。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pet_age_months:
                  type: integer
                  description: 寵物年齡 (月)
                  example: 18
                pet_weight_kg:
                  type: number
                  format: float
                  description: 寵物體重 (公斤)
                  example: 12.5
                species:
                  type: string
                  description: 寵物物種 (dog/cat/other)
                  example: dog
              required:
                - pet_age_months
                - pet_weight_kg
                - species
      responses:
        '200':
          description: 成功取得推薦列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  pet_age_months:
                    type: integer
                  species:
                    type: string
                  predicted_task_prob_walk:
                    type: number
                    format: float
                    description: 預測散步任務的機率
                  recommendations:
                    type: array
                    items:
                      type: string
                example:
                  pet_age_months: 18
                  species: dog
                  predicted_task_prob_walk: 0.75
                  recommendations:
                    - "定期散步與運動"
                    - "監控飲食與飲水"
                    - "定期梳毛"
        '400':
          description: 無效的請求參數
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 內部伺服器錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
